on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build and push'
        required: false
        default: ''

permissions:
  contents: read  

env:
  GITHUB_ACTION_TAG: ${{ github.ref_name || inputs.tag }}

jobs:
  push-multiarch:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Build and push image
      uses: rancher/ecm-distro-tools/actions/publish-image@master
      env:
        SRC: "${{ github.token }}@github.com/brooksn/Kubernetes-dns"
      with:
        image: hardened-dns-node-cache
        tag: ${{ github.event.release.tag_name || inputs.tag }}
        public-repo: ${{ secrets.DOCKER_USERNAME }}
        public-username: ${{ secrets.DOCKER_USERNAME }}
        public-password: ${{ secrets.DOCKER_PAT }}
        push-to-prime: false
